"use client";
import { BarChart3, Building2, CalendarDays, CheckSquare, LayoutDashboard, Menu, Settings, Sparkles, type LucideIcon } from "lucide-react";
import { useState } from "react";
import { cn } from "@/lib/utils";
import Link from "next/link";

const nav: Array<[string, string, LucideIcon]> = [["Dashboard", "/", LayoutDashboard], ["Clients", "/clients", Building2], ["Tasks", "/tasks", CheckSquare], ["Calendar", "#", CalendarDays], ["Reports", "#", BarChart3], ["Settings", "#", Settings]];
export function AppShell({ children }: { children: React.ReactNode }) {
 const [open, setOpen] = useState(false);
 return <div className="min-h-screen lg:flex"><aside className={cn("fixed inset-y-0 z-30 w-64 bg-navy px-4 py-6 text-white transition-transform lg:static lg:translate-x-0", open ? "translate-x-0" : "-translate-x-full")}><div className="mb-10 flex items-center gap-3 px-2"><div className="grid h-9 w-9 place-items-center rounded-lg bg-white text-navy"><Sparkles size={19}/></div><div><p className="font-bold">Newway Agri</p><p className="text-xs text-blue-200">Operations ERP</p></div></div><nav className="space-y-1">{nav.map(([label, href, Icon], i) => <Link href={href} key={label} className={cn("flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm font-medium", i === 0 ? "bg-white/15 text-white" : "text-blue-100 hover:bg-white/10")}><Icon size={18}/>{label}</Link>)}</nav><div className="absolute bottom-6 flex items-center gap-3 px-2"><div className="grid h-9 w-9 place-items-center rounded-full bg-steel font-bold">P</div><div><p className="text-sm font-semibold">Piyush</p><p className="text-xs text-blue-200">Owner · Admin</p></div></div></aside>{open && <button aria-label="Close navigation" onClick={() => setOpen(false)} className="fixed inset-0 z-20 bg-slate-900/30 lg:hidden"/>}<main className="min-w-0 flex-1"><header className="flex h-16 items-center justify-between border-b bg-white px-4 sm:px-8"><button aria-label="Open navigation" onClick={() => setOpen(true)} className="lg:hidden"><Menu/></button><div className="hidden sm:block"><p className="text-sm font-semibold text-slate-800">Tuesday, 26 August 2026</p><p className="text-xs text-slate-500">Keep every launch moving.</p></div><div className="rounded-full bg-amber-50 px-3 py-1.5 text-xs font-semibold text-amber-800">6 tasks due this week</div></header>{children}</main></div>;
}
