export type TaskStatus = "Not Started" | "In Progress" | "Blocked" | "Done";
export type Priority = "High" | "Medium" | "Low";
export type Task = { id: string; client: string; lane: string; title: string; priority: Priority; status: TaskStatus; due: string | null };

export const lanes = ["Campaigns", "Voice AI", "Content Production", "Calendar + Strategy", "Lead-Gen Strategy", "SEO / Digital Setup", "Incentive & Trust", "Client Prep"];
export const clients = ["Nuziveedu", "Kaveri", "Western Bio", "Western Agri", "Nidhi Seeds", "Laxmi Seeds", "Verdesian", "Excel Ag", "Kurnool Seeds", "Rubisco", "Astoria", "Manduca", "QH", "Best Buy Skips", "Cyagro", "Nidhi Kitchen Garden"];
const rows: Array<[string, string, string, Priority, TaskStatus, string | null]> = [
 ["Nuziveedu","Campaigns","Mustard campaign on Truecaller (with Ankita)","High","In Progress","2026-08-27"],["Nuziveedu","Voice AI","Replace call centre with AI calling (meeting)","High","In Progress","2026-09-01"],["Kaveri","Client Prep","Office visit: new campaign ideas + past reports","High","Not Started",null],["Western Bio","Campaigns","Full mustard campaign on Meta + AI voice-calling to leads","High","Not Started",null],["Western Agri","Campaigns","Full cumin campaign on Meta + AI voice-calling to leads","High","Not Started",null],["Nidhi Seeds","Content Production","Micro-drama with spicy script","Medium","In Progress","2026-09-01"],["Nidhi Seeds","Incentive & Trust","Farmer incentive: QR in pouch for lucky draw","Medium","In Progress","2026-09-01"],["Nidhi Seeds","Campaigns","Cumin campaign — Gujarat & Rajasthan (plan + creative)","High","In Progress","2026-09-01"],["Nidhi Seeds","Campaigns","Coriander campaign — Madhya Pradesh","High","In Progress","2026-09-01"],["Nidhi Seeds","Campaigns","Mustard campaign — Rajasthan & MP","High","In Progress","2026-09-01"],["Nidhi Seeds","Incentive & Trust","Product-authenticity check for farmers","Medium","In Progress","2026-09-01"],["Laxmi Seeds","Content Production","New micro-drama proposal + more videos","Medium","Not Started",null],["Verdesian","Calendar + Strategy","Monthly calendar + new strategy","Medium","Not Started",null],["Excel Ag","Calendar + Strategy","Monthly calendar + new strategy","Medium","Not Started",null],["Kurnool Seeds","Voice AI","Pitch Voice AI","High","Not Started",null],["Kurnool Seeds","Campaigns","WhatsApp campaign execution","Medium","Not Started",null],["Kurnool Seeds","Content Production","Speed up content deliveries","Medium","Not Started",null],["Rubisco","Calendar + Strategy","Monthly calendar","Medium","Not Started",null],["Cyagro","Calendar + Strategy","Monthly calendar","Medium","Not Started",null],["Astoria","Lead-Gen Strategy","More-leads strategy (ads plan done)","Medium","Not Started",null],["Manduca","Lead-Gen Strategy","More-leads strategy (ads plan done)","Medium","Not Started",null],["QH","Lead-Gen Strategy","Create ads plan + leads strategy","High","Not Started",null],["Best Buy Skips","SEO / Digital Setup","SEO + Google Ads + Meta + GMB setup","High","Not Started",null],["Nidhi Kitchen Garden","SEO / Digital Setup","SEO plan","Medium","Not Started",null]
];
export const seedTasks: Task[] = rows.map(([client,lane,title,priority,status,due], i) => ({ id: String(i + 1), client, lane, title, priority, status, due }));
